# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:13
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user #We are to use environmental vairables here
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db